### ISSUE TITLE
Error finding out Gerrit version due to port parameter

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-elk#121]
Using `elasticgirl.19` I've seen that the Gerrit collection and enrichment is not working. This is due to the following GrimoireELK error:

```
2017-11-14 10:49:18,497 - perceval.backends.core.gerrit - ERROR - gerrit cmd ssh  -p 29418 owlbot@review.gluster.org gerrit  version  failed: Command 'ssh  -p 29418 owlbot@review.gluster.org gerrit  version ' returned non-zero exit status 255                                           
ssh: connect to host review.gluster.org port 29418: No route to host                           
2017-11-14 10:50:18,676 - perceval.backends.core.gerrit - ERROR - gerrit cmd ssh  -p 29418 owlbot@review.gluster.org gerrit  version  failed: Command 'ssh  -p 29418 owlbot@review.gluster.org gerrit  version ' returned non-zero exit status 255                                           
2017-11-14 10:52:18,771 - grimoire_elk.arthur - ERROR - Error feeding ocean from gerrit (review.gluster.org): ssh  -p 29418 owlbot@review.gluster.org gerrit  version  failed 3 times. Giving up!                                            
Traceback (most recent call last):             
  File "./grimoire_elk/arthur.py", line 130, in feed_backend                                   
    ocean_backend.feed()                       
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed                                    
    for item in items:                         
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.3-py3.4.egg/perceval/backend.py", line 360, in decorator                                                                          
    for data in func(self, *args, **kwargs):   
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.3-py3.4.egg/perceval/backends/core/gerrit.py", line 88, in fetch                                                                  
    if self.client.version[0] == 2 and self.client.version[1] == 8:                            
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.3-py3.4.egg/perceval/backends/core/gerrit.py", line 339, in version                                                               
    raw_data = self.__execute(cmd)             
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.3-py3.4.egg/perceval/backends/core/gerrit.py", line 325, in __execute                                                             
    raise RuntimeError(cmd + " failed " + str(self.MAX_RETRIES) + " times. Giving up!")        
RuntimeError: ssh  -p 29418 owlbot@review.gluster.org gerrit  version  failed 3 times. Giving up!  
```

I've manually executed the command with the same result. But, if we remove the port it works ...
```
$ docker exec -it glusterfs_mordred_1 ssh  -p 29418 owlbot@review.gluster.org gerrit  version                                        
ssh: connect to host review.gluster.org port 29418: No route to host                           
$ docker exec -it glusterfs_mordred_1 ssh owlbot@review.gluster.org gerrit  version                                                  
gerrit version 2.13.9      
```

**Comment by sanacl** [comment]
Well .. maybe this is Mordred bug instead of GrimoireELK one ..

**Comment by valeriocos** [comment]
There is no trace of similar errors in the production logs, should we close this issue? @acs

**Comment by acs** [comment]
Yes, I think it was fixed by a change in gerrit backend some weeks ago. 

Closing it... if the errors reappears @sanacl reopen the ticket.
