### ISSUE TITLE
NoneType error analyzing Maniphest

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-elk#138]
How to reproduce:

* version: elasticgirl.23
* sources: Bitergia's phabricator

Traceback:
```
2017-11-28 16:46:43,365 - grimoire_elk.arthur - ERROR - Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 489, in enrich_backend
    enrich_count = enrich_items(ocean_backend, enrich_backend)
  File "./grimoire_elk/arthur.py", line 304, in enrich_items
    total= enrich_backend.enrich_items(ocean_backend)
  File "./grimoire_elk/elk/enrich.py", line 376, in enrich_items
    rich_item = self.get_rich_item(item)
  File "./grimoire_elk/elk/phabricator.py", line 254, in get_rich_item
    self.__fill_phab_ids(item['data'])
  File "./grimoire_elk/elk/phabricator.py", line 235, in __fill_phab_ids
    self.phab_ids_names[p['phid']] = p['name']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sanacl** [comment]
The issue is related to fields containing a list with None values. We end up with this variables due to the Data stored in ES sometimes has a '[null]' which in ES is the same as '[]'. Unfortunately this is not the case in Python, so we iterate the list and it crashes. A general solution would be avoiding having [null] and forcing '[]'.

This can be reproduced getting the ticket T287 of Bitergia's dashboard.

**Comment by acs** [comment]
Fixed in https://github.com/grimoirelab/GrimoireELK/commit/84a1d736afdb11b23ea0e081bcb6ff01d415d27d

**Comment by sanacl** [comment]
Executing the same scenario I got the same error in a different line. 🤕 

```
2017-11-29 15:16:02,272 - grimoire_elk.arthur - ERROR - Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 489, in enrich_backend
    enrich_count = enrich_items(ocean_backend, enrich_backend)
  File "./grimoire_elk/arthur.py", line 304, in enrich_items
    total= enrich_backend.enrich_items(ocean_backend)
  File "./grimoire_elk/elk/enrich.py", line 376, in enrich_items
    rich_item = self.get_rich_item(item)
  File "./grimoire_elk/elk/phabricator.py", line 255, in get_rich_item
    self.__fill_phab_ids(item['data'])
  File "./grimoire_elk/elk/phabricator.py", line 235, in __fill_phab_ids
    if 'name' in p and 'phid' in p:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by valeriocos** [comment]
There is no trace of similar errors in the production logs. I guess the issue was solved at some point in the past.
