### ISSUE TITLE
Elasticsearch 6.x and bulk indexing

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-elk#156]
Bulk indexing is broken when using ES 6 (6.1.1) grimoirelab/perceval#270

The error can be reproduced by executing the method _test_run_ in [mordred/tests/test_task_collection.py](https://github.com/grimoirelab/mordred/blob/master/tests/test_task_collection.py)

```
INFO:grimoire_elk.arthur:Feeding Ocean from git (https://github.com/grimoirelab/GrimoireELK)
ERROR:grimoire_elk.elk.elastic:Error creating ES mappings {"error":"Content-Type header [] is not supported","status":406}
WARNING:grimoire_elk.elk.elastic:Can add mapping http://localhost:9200/git_test-raw/items/_mapping: 
        {
          "dynamic_templates": [
            { "notanalyzed": {
                  "match": "*",
                  "match_mapping_type": "string",
                  "mapping": {
                      "type":        "string",
                      "index":       "not_analyzed"
                  }
               }
            }
          ]
        } 
INFO:grimoire_elk.ocean.conf:Creating OceanConf index http://localhost:9200/conf
INFO:grimoire_elk.ocean.elastic:Incremental from: None
INFO:perceval.backends.core.git:Fetching commits: 'https://github.com/grimoirelab/GrimoireELK' git repository from 1970-01-01 00:00:00+00:00; all branches
INFO:grimoire_elk.ocean.elastic:Adding items to Ocean for <grimoire_elk.ocean.git.GitOcean object at 0x7fc1928176d8> (100 items)
Traceback (most recent call last):
  File "../grimoire_elk/arthur.py", line 196, in feed_backend
    ocean_backend.feed()
  File "../grimoire_elk/ocean/elastic.py", line 201, in feed
    self.feed_items(items)
  File "../grimoire_elk/ocean/elastic.py", line 219, in feed_items
    self._items_to_es(items_pack)
  File "../grimoire_elk/ocean/elastic.py", line 247, in _items_to_es
    self.elastic.bulk_upload_sync(json_items, field_id)
  File "../grimoire_elk/elk/elastic.py", line 195, in bulk_upload_sync
    total += self.bulk_upload(items_pack, field_id)
  File "../grimoire_elk/elk/elastic.py", line 137, in bulk_upload
    self._safe_put_bulk(url, bulk_json)
  File "../grimoire_elk/elk/elastic.py", line 101, in _safe_put_bulk
    res.raise_for_status()
  File "/home/slimbook/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: http://localhost:9200/git_test-raw/items/_bulk
ERROR:grimoire_elk.arthur:Error feeding ocean from git (https://github.com/grimoirelab/GrimoireELK): 406 Client Error: Not Acceptable for url: http://localhost:9200/git_test-raw/items/_bulk
```

**Comment by valeriocos** [comment]
Closing this issue, the error cannot be replicated and the recent logs are empty. It was probably due to a mapping coming from an old version of ES
