### ISSUE TITLE
[pipermail] Encoding errors during enrichment phase

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#320]
Running an analysis of some public [Ubuntu mailing lists](https://lists.ubuntu.com/), I am getting some error messages like the following one during pipermail enrichment phase:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udca8' in position 146: surrogates not allowed
Call stack:
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/mordred/task_manager.py", line 92, in run
    task.execute()
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/mordred/task_enrich.py", line 255, in execute
    self.__enrich_items()
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/mordred/task_enrich.py", line 135, in __enrich_items
    pair_programming=pair_programming)
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/elk.py", line 583, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/elk.py", line 393, in load_identities
    enrich_backend.get_connector_name())
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/sortinghat_gelk.py", line 118, in add_identities
    cls.add_identity(db, identity, backend)
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/sortinghat_gelk.py", line 77, in add_identity
    uuid, identity['username'], identity['name'], identity['email'])
Message: 'New sortinghat identity %s %s,%s,%s '
Arguments: ('eeff557c5aef4914157311fd881bab39a053453c', None, ' T\udca8\udcb2lio Henrique ', '******@gmail.com')
```
(email address was hide, for privacy reasons)

**Comment by acs** [comment]
Could you specify the mailing list? Or it happens with several mailing lists?

**Comment by jsmanrique** [comment]
That's all the log info I have. So I don't know which one is failing. I can share the projects.json file with you: [ubuntu-projects.zip](https://github.com/chaoss/grimoirelab-elk/files/1916195/ubuntu-projects.zip)

**Comment by valeriocos** [comment]
better late than never, I have executed the raw and enrich phases with micro-mordred over the set of projects you shared @jsmanrique . No error was detected, so the issue can be closed.
