### ISSUE TITLE
[Stackexchange] Issue getting user['display_name']

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#336]
Analyzing [Ubuntu StackExchange instance](https://askubuntu.com/) with Grimoire Mordred, I get the following error message:
```
Collection for stackexchange: finished after 01:13:51 hours
Enrichment for stackexchange: starting...
2018-04-30 10:07:13,609 - grimoire_elk.elk - ERROR - Traceback (most recent call last):
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/elk.py", line 583, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/elk.py", line 380, in load_identities
    identities = enrich_backend.get_identities(item)
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/stackexchange.py", line 108, in get_identities
    user = self.get_sh_identity(answer[identity])
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/stackexchange.py", line 90, in get_sh_identity
    identity['username'] = user['display_name']
KeyError: 'display_name'

2018-04-30 10:07:13,637 - grimoire_elk.elk - ERROR - Error enriching ocean from stackexchange (askubuntu.com): 'display_name'
Elasticsearch aliases for stackexchange: creating...
Elasticsearch aliases for stackexchange: created!
```
It seems it's expecting a `user['display_name']` and it's empty or it doesn't even exists..

**Comment by acs** [comment]
@valeriocos could you take a look?
