### ISSUE TITLE
Issue indexing a specific PR, NoneType is not subscriptable

### ISSUE THREAD

**Issue by GregSutcliffe** [chaoss/grimoirelab-elk#523]
I'm trying to index a large repo (see #522 for details) and I've made progress using `--from-date`. Now I'm hitting an error with a specific PR:

```
2018-11-19 14:16:15,519 Get GitHub paginated items from https://api.github.com/repos/ansible/ansible/pulls/41441/comments
2018-11-19 14:16:15,637 Archiving e85fc673592f5e97d55c0287dbffc6478ada41ff with https://api.github.com/repos/ansible/ansible/pulls/41441/comments {'per_page': 100, 'direction': 'asc', 'sort':
 'updated'} None in /root/.perceval/archives/ad/54899fcabb4a159c4573e122139d39.sqlite3
2018-11-19 14:16:15,641 e85fc673592f5e97d55c0287dbffc6478ada41ff data archived in /root/.perceval/archives/ad/54899fcabb4a159c4573e122139d39.sqlite3
2018-11-19 14:16:15,641 Rate limit: 4611
2018-11-19 14:16:15,641 Rate limit reset: 3532.0
2018-11-19 14:16:15,642 Error feeding ocean from github (https://github.com/ansible/ansible): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/grimoirelab/lib/python3.5/site-packages/grimoire_elk/elk.py", line 201, in feed_backend
    ocean_backend.feed(from_date, category=category)  
  File "/opt/grimoirelab/lib/python3.5/site-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/opt/grimoirelab/lib/python3.5/site-packages/grimoire_elk/raw/elastic.py", line 211, in feed_items
    for item in items:
  File "/opt/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs): 
  File "/opt/grimoirelab/lib/python3.5/site-packages/perceval/backends/core/github.py", line 257, in __fetch_pull_requests
    pull[field + '_data'] = self.__get_pull_review_comments(pull['number'])
  File "/opt/grimoirelab/lib/python3.5/site-packages/perceval/backends/core/github.py", line 373, in __get_pull_review_comments
    comment['user_data'] = self.__get_user(comment['user']['login'])
TypeError: 'NoneType' object is not subscriptable
2018-11-19 14:16:15,658 Done github
2018-11-19 14:16:15,659 Backend feed completed
```

I don't really know how to troubleshoot this, as I'm not really sure what it's trying to do... any ideas?

**Comment by valeriocos** [comment]
@GregSutcliffe thank you for reporting this issue.

The error is due to a pull request comment which doesn't contain the user attribute (`comment['user']['login']`) (see last comment at: https://api.github.com/repos/ansible/ansible/pulls/41441/comments). 

Checking the PR in GitHub (https://github.com/ansible/ansible/pull/41441), the user appears as ghost (which is the default user for those accounts that were deleted). Generally the GitHub API returns for those users, data that looks like: https://api.github.com/users/ghost. However in this case it seems that no data is included in the pull request comment. 

Could you open an issue in [grimoirelab-perceval](https://github.com/chaoss/grimoirelab-perceval/tree/master/perceval), so we can investigate the error and prepare a fix if needed?

If you are working with the source code a possible work-around could be to filter this comment. To do so,
at the line: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L372, you could have something similar to:
```
if not 'user' in comment:
   logger.warning("Skipping comment ....")
   continue
```

**Comment by GregSutcliffe** [comment]
Thanks for the explanation. I've opened https://github.com/chaoss/grimoirelab-perceval/issues/459 to track it.

I'm out of time for today, but I'll see about adding the workaround to the source tomorrow. Thanks!

**Comment by valeriocos** [comment]
great! thank you @GregSutcliffe . I'm going to close this issue, feel free to reopen it if needed.
