### ISSUE TITLE
404 API exception not handled for Github repos

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#550]
When a repository does not exist we are getting an error. The exception should be handled in order to avoid breaking the update process and an error message should be printed to error log.

Related issues: #551, #552, #553, #554, #555, #556

This is the traceback:
```
Error feeding ocean from github (https://github.com/hashicorp/vault-plugin-spiffe-auth): 404 Client Error: Not Found for url: https://api.github.com/repos/hashicorp/vault-plugin-spiffe-auth/issues?per_page=100&sort=updated&direction=asc&state=all&since=2018-03-11T04%3A02%3A53%2B00%3A00
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 207, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 218, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 225, in __fetch_issues
    for raw_issues in issues_groups:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 683, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 667, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/hashicorp/vault-plugin-spiffe-auth/issues?per_page=100&sort=updated&direction=asc&state=all&since=2018-03-11T04%3A02%3A53%2B00%3A00
```

**Comment by valeriocos** [comment]
Error already handled: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L207
