### ISSUE TITLE
401 API exception not handled for Github repos

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#551]
When the software founds a Github repo asking for credentials and return a 401, the software is crashing instead of handling the exception. The exception should be handled and an error message should be printed to error log.

Related issues: #550, #552, #553, #554, #555, #556

This is the traceback:

```
Error feeding ocean from git (https://github.com/sudopluto/udacity-cs212-polygot.git): unexpected http response 401 for https://github.com/sudopluto/udacity-cs212-polygot.git/info/refs?service=git-upload-pack
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1261, in _http_request
    resp = self.opener.open(req)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 193, in feed_backend
    ocean_backend.feed(latest_items=latest_items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 218, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 155, in fetch_items
    latest_items, no_update)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 273, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 310, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 926, in sync
    pack_name, refs = self._fetch_pack()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1104, in _fetch_pack
    fd.write)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1398, in fetch_pack
    b"git-upload-pack", url)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1282, in _discover_references
    resp, read = self._http_request(url, headers, allow_compression=True)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1267, in _http_request
    (e.code, url))
dulwich.errors.GitProtocolError: unexpected http response 401 for https://github.com/sudopluto/udacity-cs212-polygot.git/info/refs?service=git-upload-pack
```

**Comment by valeriocos** [comment]
Error already handled: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L207
