### ISSUE TITLE
requests.exceptions.HTTPError is not handled

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#554]
When the exception **requests.exceptions.HTTPError** is raised, the code in grimoirelab-elk crashes instead of handling the exception. The exception should be handled and an error message should be printed to error log. 

Related issues: #550, #551, #553, #553, #555, #556

This is the traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 207, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 211, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 245, in __fetch_issues
    issue[field + '_data'] = self.__get_issue_comments(issue['number'])
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 311, in __get_issue_comments
    self.__get_issue_comment_reactions(comment_id, comment['reactions']['total_count'])
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 326, in __get_issue_comment_reactions
    for raw_reactions in group_reactions:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 682, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 666, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.github.com/repos/rust-lang/rfcs/issues/comments/274399283/reactions?sort=updated&direction=asc&per_page=100
```

This exception is pretty interesting because it can be caused due to 5xx errors so when it is caught we should define what's better to do.

**Comment by valeriocos** [comment]
Error already handled: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L207
