### ISSUE TITLE
http.client.IncompleteRead is not handled

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#555]
This error is less common than the bugs mentioned below but it could lead to unexpected results, it could be related to 5xx errors but to be honest I'm not sure. If that's the case maybe it is a good idea to apply the same solution provided for #554

Related issues: #550, #551, #553, #553, #554, #556

This is the traceback:
```
Error feeding ocean from git (https://github.com/opendatakit/xlsform-server.git): IncompleteRead(0 bytes read)
Traceback (most recent call last):
  File "/usr/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.5/http/client.py", line 508, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/http/client.py", line 573, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.5/http/client.py", line 543, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 193, in feed_backend
    ocean_backend.feed(latest_items=latest_items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 211, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 149, in fetch_items
    latest_items)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 267, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 303, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 914, in sync
    pack_name, refs = self._fetch_pack()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1052, in _fetch_pack
    fd.write)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1398, in fetch_pack
    b"git-upload-pack", url)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 1309, in _discover_references
    return read_pkt_refs(proto) + (base_url, )
  File "/usr/local/lib/python3.5/dist-packages/dulwich/client.py", line 197, in read_pkt_refs
    for pkt in proto.read_pkt_seq():
  File "/usr/local/lib/python3.5/dist-packages/dulwich/protocol.py", line 254, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/usr/local/lib/python3.5/dist-packages/dulwich/protocol.py", line 200, in read_pkt_line
    sizestr = read(4)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 589, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)
```

**Comment by valeriocos** [comment]
Error already handled: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L207
