### ISSUE TITLE
perceval.errors.RateLimitError exception is not properly handled

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#556]
When the exception **perceval.errors.RateLimitError** is raised, the code in grimoirelab-elk crashes instead of handling the exception. The exception should be handled and an error message should be printed to error log.

Related issues: #550, #551, #553, #553, #554, #555

This is the traceback:
```
Error feeding ocean from github (https://github.com/symphonyoss/bot-room-manager): Rate limit exhausted.; 701.0 seconds to rate reset
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 207, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 211, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 225, in __fetch_issues
    for raw_issues in issues_groups:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 682, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 664, in fetch
    self.sleep_for_rate_limit()
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 266, in sleep_for_rate_limit
    raise RateLimitError(cause=cause, seconds_to_reset=seconds_to_reset)
perceval.errors.RateLimitError: Rate limit exhausted.; 701.0 seconds to rate reset
```

**Comment by valeriocos** [comment]
Error already handled: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L207
