### ISSUE TITLE
perceval.backends.core.slack.SlackClientError exception is not handled

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#558]
When the exception **perceval.backends.core.slack.SlackClientError** is raised, the code in grimoirelab-elk crashes instead of handling the exception. The exception should be handled and an error message should be printed to error log. It is critical to catch this exception to make sure our team is aware of a possible issue with the setup due to a wrong or expired token.

Related issues: #550, #551, #552, #553, #553, #554, #555

This is the traceback:
```
Error feeding ocean from slack (https://slack.com/C0NNRDKLN): token_revoked
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 207, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 218, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/slack.py", line 112, in fetch_items
    raw_info = self.client.channel_info(self.channel)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/slack.py", line 353, in channel_info
    response = self._fetch(resource, params)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/slack.py", line 424, in _fetch
    raise SlackClientError(error=result['error'])
perceval.backends.core.slack.SlackClientError: token_revoked
```

**Comment by valeriocos** [comment]
Error already handled: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L207
