### ISSUE TITLE
RepositoryError: git command - Cloning into bare repository

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#720]
I am playing with latest GrimoireLab/mordred release (0.2.32) and when analyzing [Open Distro for Elasticsearch](https://github.com/opendistro-for-elasticsearch) repositories, I get this message in mordred logs:
```
2019-10-31 00:11:07,631 - grimoire_elk.elk - ERROR - Error feeding raw from git (https://github.com/opendistro-for-elasticsearch/sql.git): git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/https://github.com/opendistro-for-elasticsearch/sql.git-git'...
mordred_1        | fatal: could not read Username for 'https://github.com': No such device or address
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
mordred_1        |     ocean_backend.feed(**params)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
mordred_1        |     self.feed_items(items)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
mordred_1        |     for item in items:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
mordred_1        |     for item in self.fetch_items(category, **kwargs):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 154, in fetch_items
mordred_1        |     latest_items, no_update)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 267, in __fetch_from_repo
mordred_1        |     repo = self.__create_git_repository()
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 318, in __create_git_repository
mordred_1        |     repo = GitRepository.clone(self.uri, self.gitpath)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 826, in clone
mordred_1        |     cls._exec(cmd, env=env)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1331, in _exec
mordred_1        |     raise RepositoryError(cause=cause)
mordred_1        | perceval.errors.RepositoryError: git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/https://github.com/opendistro-for-elasticsearch/sql.git-git'...
mordred_1        | fatal: could not read Username for 'https://github.com': No such device or address```

Any clue about what could be happening?

**Comment by valeriocos** [comment]
Thank you @jsmanrique for reporting this issue. I'm not able to replicate it, maybe you experienced a connection problem. Could you (i) execute only Perceval on that repo, (ii) share your setup.cfg and projects.json?

I tried with the following ones and it worked smoothly.
```
{
    "ACME": {
        "git": [
            "https://github.com/opendistro-for-elasticsearch/sql",
            "https://github.com/opendistro-for-elasticsearch/performance-analyzer",
            "https://github.com/opendistro-for-elasticsearch/index-management"
        ],
        ....
```
```
[git]
raw_index = git_acme
enriched_index = git_acme_enriched
latest-items = true
category = commit
```

Thanks

**Comment by jsmanrique** [comment]
Thank you very much @valeriocos. I have looked at the data this morning, and it seems to be working smoothly. So, you might be right and there might be some connection issues between my AWS Lightsail instance and the repositories. I think we could close this issue ;-)

**Comment by valeriocos** [comment]
great, thanks for the quick reply!
