### ISSUE TITLE
ERROR - Error feeding raw from pipermail 

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#721]
Analyzing activity in [gtk mailing list](https://mail.gnome.org/archives/gtk-list/), I am getting this error message in mordred logs:

```
mordred_1        | 2019-11-05 21:23:47,303 - grimoire_elk.elk - ERROR - Error feeding raw from pipermail (https://mail.gnome.org/archives/gtk-list/): offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
mordred_1        |     ocean_backend.feed(**params)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
mordred_1        |     self.feed_items(items)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
mordred_1        |     for item in items:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
mordred_1        |     for item in self.fetch_items(category, **kwargs):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/pipermail.py", line 108, in fetch_items
mordred_1        |     for message in messages:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 229, in _fetch_and_parse_messages
mordred_1        |     raise e
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 211, in _fetch_and_parse_messages
mordred_1        |     if dt < from_date:
mordred_1        | ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
```

I don't know what to do, and I don't even know what impact does this has in the data quality.

**Comment by valeriocos** [comment]
Thank you @jsmanrique for reporting this issue. The error originates in Perceval, I'll have a look and provide a fix

**Comment by valeriocos** [comment]
Related to https://github.com/chaoss/grimoirelab-toolkit/pull/22
