### ISSUE TITLE
Error enriching ocean from telegram / Error feeding raw from telegram

### ISSUE THREAD

**Issue by antonionardella** [chaoss/grimoirelab-elk#779]
Hello,

I am using the grimoirelab/full docker container.
This is the backend configuration:

projects.json
```
        "telegram": [
            "[REDACTED BOT NAME]"
        ]
```

credentials.cfg
``` 
[telegram]
api-token = [REDACTED BOT API TOKEN]
raw_index = telegram_iota_raw
enriched_index = telegram_iota_enriched

```

I get these errors in the logs:

* username

```
grimoire       | 2020-02-05 15:48:34,978 - grimoire_elk.elk - ERROR - Error enriching ocean from telegram (https://telegram.org/[REDACTED]): 'username'
grimoire       | Traceback (most recent call last):
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 657, in enrich_backend
grimoire       |     total_ids = load_identities(ocean_backend, enrich_backend)
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 415, in load_identities
grimoire       |     for identity in identities:
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/telegram.py", line 80, in get_identities
grimoire       |     identity = self.get_sh_identity(message['from'])
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/telegram.py", line 69, in get_sh_identity
grimoire       |     identity['username'] = from_['username']
grimoire       | KeyError: 'username'
```

* message_id
```
grimoire       | 2020-02-05 15:48:24,612 - grimoire_elk.elk - ERROR - Error feeding raw from telegram (https://telegram.org/[REDACTED]): 'message'
grimoire       | Traceback (most recent call last):
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
grimoire       |     ocean_backend.feed(**params)
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
grimoire       |     self.feed_items(items)
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
grimoire       |     for item in items:
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 219, in fetch
grimoire       |     metadata_item = self.metadata(item, filter_classified=filter_classified)
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/telegram.py", line 165, in metadata
grimoire       |     item = super().metadata(item, filter_classified=filter_classified)
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 323, in metadata
grimoire       |     'uuid': uuid(self.origin, self.metadata_id(item)),
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/telegram.py", line 190, in metadata_id
grimoire       |     return str(item['message']['message_id'])
grimoire       | KeyError: 'message'
```

And the bot has been added to a public Telegram group with 1418 members.

What can I check?

Thank you,
Antonio

**Comment by valeriocos** [comment]
Hi @ioiobzit , I was able to replicate the first error but not the second one.

- The first error is due to the fact that `username` is an optional field (https://core.telegram.org/bots/api#user), which the code assumes to be always there.

- The second error is also due to an optional field assumed to be there, in this case `message`. Find below some more details.

   The perceval backend works in the following way:
  - The updates on the channel are fetched using the endpoint [getupdates](https://core.telegram.org/bots/api#getupdates), which returns a list of [Updates](https://core.telegram.org/bots/api#update)
  - Each `Update` contains an `update_id` and optionally a `Message` (among other things).
  - Each `Message` contains an `message_id`, that is used to [identify](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/telegram.py#L190) the item produced by Perceval. 

  Thus, an error is thrown when looking for a `message_id` into an `Update` without a `Message`.
