### ISSUE TITLE
Docker image fails to create Elastic Search index

### ISSUE THREAD

**Issue by marceloschmidt** [chaoss/grimoirelab-elk#79]
`sudo docker run --name gelk -it --rm --link elasticsearch:elasticsearch --link mariadb:mariadb --link redis:redis bitergia/gelk`

```
Traceback (most recent call last):
  File "arthur/bin/arthurd", line 209, in <module>
    main()
  File "arthur/bin/arthurd", line 84, in main
    writer = ElasticItemsWriter(args.es_index)
  File "/home/bitergia/arthur/arthur/writers.py", line 98, in __init__
    was_created = self.create_index(self.idx_url, clean=clean)
  File "/home/bitergia/arthur/arthur/writers.py", line 173, in create_index
    raise ElasticSearchError(cause=cause)
arthur.writers.ElasticSearchError: Error creating Elastic Search index http://elasticsearch:9200/ocean
```

**Comment by valeriocos** [comment]
Sorry for the late reply, the error seems to be gone time ago. Feel free to open a new one if needed.
