### ISSUE TITLE
Groups.io "invalid start_time format" error when running using resume mode.

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-elk#795]
When attempting to get data from groups.io using `p2o.py` it tries to resume from where it left since last run and gets the following error:
`p2o.py --enrich --index sds-lfai-acumos-groupsio-raw --index-enrich sds-lfai-acumos-groupsio -e [redacted] -g --scroll-size 1000 --db-host [redacted] --db-sortinghat [redacted] --db-user [redacted] --db-password [redacted] groupsio deeplearningfoundation+acumosai-announce`
```
2020-03-06 06:12:03,396 Debug mode activated
2020-03-06 06:12:03,396 Feeding raw from groupsio ([redacted])
2020-03-06 06:12:03,496 Found version of ES instance at [redacted]: 7.
2020-03-06 06:12:03,668 [redacted]sds-lfai-acumos-groupsio-raw/_search 
        { "size": 0, "query": {"bool": {"filter": [{"term" : { "origin" : "https://groups.io/g/deeplearningfoundation+acumosai-announce"}}]}},  
            "aggs": {
                "1": {
                  "max": {
                    "field": "metadata__updated_on"
                  }
                }
            }
        
        } 
2020-03-06 06:12:03,697 [groupsio] Incremental from: 2019-05-20 14:02:10+00:00 for https://groups.io/g/deeplearningfoundation+acumosai-announce
2020-03-06 06:12:03,697 Looking for messages from 'https://groups.io/g/deeplearningfoundation+acumosai-announce' since 2019-05-20 14:02:10
2020-03-06 06:12:04,192 Groupsio email [redacted] authenticated in https://groups.io/api/v1
2020-03-06 06:12:04,192 Downloading mboxes from 'https://groups.io/g/deeplearningfoundation+acumosai-announce'
2020-03-06 06:12:04,193 Storing mboxes in '/root/.perceval/mailinglists/https://groups.io/g/deeplearningfoundation+acumosai-announce'
2020-03-06 06:12:04,193 Get groupsio paginated subscriptions from https://groups.io/api/v1/getsubs
2020-03-06 06:12:04,468 Subscriptions: 100/148
2020-03-06 06:12:04,726 Impossible to download archives from https://groups.io/g/deeplearningfoundation+acumosai-announce. Error info: {"object":"error","type":"bad_request","extra":"invalid start_time format"}

2020-03-06 06:12:04,726 Error feeding raw from groupsio (https://groups.io/g/deeplearningfoundation+acumosai-announce): 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?start_time=2019-05-20T14%3A02%3A10&group_id=8788
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 234, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 250, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 221, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 127, in fetch_items
    mailing_list.fetch(from_date)
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 212, in fetch
    success = self._download_archive(url, payload, filepath)
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 251, in _download_archive
    raise e
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 246, in _download_archive
    r.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?start_time=2019-05-20T14%3A02%3A10&group_id=8788
```

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki , this bug has been fixed yesterday. The fix will be available in the next release (0.2.39).

https://github.com/chaoss/grimoirelab-perceval/commit/f1bdd736d4d6145f5fca81912d70137948d5ed7a

**Comment by lukaszgryglicki** [comment]
Great!
Can you ping me when that release is available? I'll generate a new base image then.
Thanks!

**Comment by valeriocos** [comment]
sure! I close this issue in the meanwhile
