### ISSUE TITLE
[gerrit] sortKey error when enriching gerrit data

### ISSUE THREAD

**Issue by code-sleuth** [chaoss/grimoirelab-elk#802]
Command:
```
p2o.py --enrich --index lfn-odl-gerrit-raw --index-enrich lfn-odl-gerrit -e [redacted] -g --scroll-size 1000 --db-host [redacted] --db-[redacted] [redacted] --db-user [redacted] --db-password [redacted] gerrit git.opendaylight.org --user [redacted]
```

Error:
```
2020-03-11 19:29:47,255 GETTING MORE REVIEWS 500 >= 500
2020-03-11 19:29:47,255 Error feeding raw from gerrit (git.opendaylight.org): 'sortKey'
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 234, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 250, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 221, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 121, in fetch_items
    for review in fetcher:
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 266, in _fetch_gerrit
    last_item = self.client.next_retrieve_group_item(last_item, review)
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 390, in next_retrieve_group_item
    next_item = entry['sortKey']
KeyError: 'sortKey'
```

**Comment by lukaszgryglicki** [comment]
Seems like it goes into the `else` branch, where it "thinks" it will find `sortkey` which was used in older Gerrit releases (< 2.9).

Code structure suggests that < 2.9 should try `sortKey`, 2.9 does not support sort key and > 2.9 handles this differently.

Gerrit instance in this example is 3.1, so it should probably fall into > 2.9 ?

Or maybe I should just add a check `'sortKey' in entry` ?

**Comment by lukaszgryglicki** [comment]
If I change `if gerrit_version[0] == 2 and gerrit_version[1] > 9:` to `if gerrit_version[0] > 2 or (gerrit_version[0] == 2 and gerrit_version[1] > 9):`

Then it assigns `next_item = 0` (for Gerrit 3.1), but then:
```
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 165, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 225, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 241, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 127, in fetch_items
    for review in fetcher:
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 250, in _fetch_gerrit
    reviews = self._get_reviews(last_item)
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 278, in _get_reviews
    raw_data = self.client.reviews(last_item, filter_)
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 370, in reviews
    cmd = self._get_gerrit_cmd(last_item, filter_)
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 494, in _get_gerrit_cmd
    cmd += " resume_sortkey:" + last_item
TypeError: Can't convert 'int' object to str implicitly
```

So I don't know how this code is supposed to work. The only thing I can do is just change:
`if entry is not None:` to `if entry is not None and 'sortkey' in entry:` in the fallback `else` clause.

That makes this work, but I'm quite sure this is just a hot-fix that will not solve the problem, so I'm not creating a PR with that change.

Somebody who known this backend (probably the author) should reevalutate how this works for at least:
- Gerrit 2.X < 2.9
- Gerrit 2.9
- Gerrit 2.X > 2.9
- Gerrit 3.X

All those Gerrit classes should be checked for paginating/resuming (like > 500 results in request and resume support when running again on the same ES instance with some data already present).

cc @valeriocos @code-sleuth @sduenas
