### ISSUE TITLE
issue loading the data to ES using p2o.py

### ISSUE THREAD

**Issue by herotest** [chaoss/grimoirelab-elk#82]
p2o.py --enrich --index git_raw --index-enrich git -e http://localhost:9200 --no_inc --debug git /tmp/git-data.json
2017-04-16 07:11:03,996 Debug mode activated
2017-04-16 07:11:03,998 Feeding Ocean from git (/tmp/git-data.json)
2017-04-16 07:11:04,553 Can't create index http://localhost:9200/git_raw (407)
2017-04-16 07:11:04,553 Error feeding ocean from git (/tmp/git-data.json): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/arthur.py", line 67, in feed_backend
    elastic_ocean = get_elastic(url, es_index, clean, ocean_backend)
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/utils.py", line 177, in get_elastic
    elastic = ElasticSearch(url, es_index, mapping, clean, insecure, analyzers)
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/elk/elastic.py", line 83, in __init__
    raise ElasticWriteException()
grimoire_elk.elk.elastic.ElasticWriteException
2017-04-16 07:11:04,557 Can't add repo to conf. Ocean elastic is not configured
2017-04-16 07:11:04,557 Done git 
2017-04-16 07:11:04,557 Backed feed completed
fatal: Not a git repository (or any of the parent directories): .git
2017-04-16 07:11:04,561 Can't get the gelk version. /usr/local/lib/python3.4/dist-packages/grimoire_elk/elk/enrich.py
2017-04-16 07:11:05,097 Can't create index http://localhost:9200/git (407)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/arthur.py", line 426, in enrich_backend
    elastic_enrich = get_elastic(url, enrich_index, clean, enrich_backend)
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/utils.py", line 177, in get_elastic
    elastic = ElasticSearch(url, es_index, mapping, clean, insecure, analyzers)
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/elk/elastic.py", line 83, in __init__
    raise ElasticWriteException()
grimoire_elk.elk.elastic.ElasticWriteException
2017-04-16 07:11:05,100 Error enriching ocean from git (/tmp/git-data.json): 
2017-04-16 07:11:05,100 Done git 
2017-04-16 07:11:05,100 Enrich backend completed
2017-04-16 07:11:05,101 Finished in 0.02 min

**Comment by herotest** [comment]
I have pulled perceval, grimoire-elk and kidash using pip3
I am able to use perceval and pull the git repo log.
When  i am trying to load  i get the below error

p2o.py --enrich --index git_raw --index-enrich git -e http://localhost:9200 --no_inc debug git 
 sbde_commit.log 
Traceback (most recent call last):
  File "/usr/local/bin/p2o.py", line 127, in <module>
    args.index, args.index_enrich, args.project)
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/arthur.py", line 53, in feed_backend
    raise RuntimeError("Unknown backend %s" % backend_name)
RuntimeError: Unknown backend debug

I have the below 

grimoire-elk (0.26.5)
grimoire-kidash (0.22.1)
perceval (0.7.0)
perceval-mozilla (0.1.0)

Am i  missing anything?

**Comment by robinmuilwijk** [comment]
Hi @herotest , you need to change "debug" to "--debug". Then try again, the rest of your command looks good.

**Comment by herotest** [comment]
Thanks Robin
But as you see the earlier message i used the --debug got a different error msg
Now i am getting a different error If i use the log file to load 

These are the commands i am using
perceval git https://github.com/grimoirelab/GrimoireELK.git > /tmp/grimoire_git.log

p2o.py --enrich --index grimoire_raw --index-enrich grimoire -e http://localhost:9200 --no_inc --debug git /tmp/grimoire.json 

2017-04-18 08:36:22,934 Incremental from: None
2017-04-18 08:36:22,936 Fetching commits: '/tmp/grimoire.json' git repository from 1970-01-01 00:00:00+00:00; all branches
2017-04-18 08:36:22,936 Error feeding ocean from git (/tmp/grimoire.json): commit expected on line 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/arthur.py", line 117, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.4/dist-packages/grimoire_elk/ocean/elastic.py", line 195, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval/backend.py", line 359, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/core/git.py", line 117, in fetch
    for commit in commits:
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/core/git.py", line 215, in parse_git_log_from_file
    for commit in parser.parse():
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/core/git.py", line 435, in parse
    parsed = self.handlers[self.state](line)
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/core/git.py", line 477, in _handle_commit
    raise ParseError(cause=msg)
perceval.errors.ParseError: commit expected on line 1


PS: if I use 
p2o.py --enrich --index grimoire_raw --index-enrich grimoire -e http://localhost:9200 --no_inc --debug git https://github.com/grimoirelab/GrimoireELK.git

it works
Only for log file i am having issue

**Comment by robinmuilwijk** [comment]
I see what you are doing differently. I am only loading the some-repository.git. Not the git log. Someone from Bitergia might know more why you are getting these errors.

**Comment by valeriocos** [comment]
@herotest , sorry for the late reply.

The command below fetches data from a local repository
```p2o.py --enrich --index git_raw --index-enrich git -e http://localhost:9200 --no_inc --debug git /.../grimoirelab-perceval-git``` 

The command below fetches data from a remote repository
```p2o.py --enrich --index git_raw --index-enrich git -e http://localhost:9200 --no_inc --debug git https://github.com/chaoss/grimoirelab-perceval(.git)``` 

The command below fetches data from a log file
```p2o.py --enrich --index git_raw --index-enrich git -e http://localhost:9200 --no_inc --debug git /../grimoirelab-perceval-git --git-log /.../log.txt``` 

To have things working, the log should be generated with:
```git log --raw --numstat --pretty=fuller --decorate=full --parents -M -C -c --remotes=origin --all```
Please, find more detail at: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L366

**Comment by valeriocos** [comment]
Closing this issue! For the future, please use micro-mordred (https://github.com/chaoss/grimoirelab-sirmordred#micro-mordred), p2o.py is being decomissioned.
