### ISSUE TITLE
[confluence] missing data due to p2o not fully enriching confluence index

### ISSUE THREAD

**Issue by code-sleuth** [chaoss/grimoirelab-elk#829]
Issue:
There is a lot of missing data in the created confluence index.

command:
```
p2o.py --enrich --index opnfv-confluence-raw --index-enrich opnfv-confluence -e [redacted] -g --scroll-size 1000 --db-host [redacted] --db-sortinghat [redacted] --db-user [redacted] --db-password [redacted] confluence https://wiki.opnfv.org
```

error:
```
2020-04-03 12:28:31,441 [confluence] Adding items to Raw for <grimoire_elk.raw.confluence.ConfluenceOcean object at 0x7fa38b130cf8> (1000 items)
2020-04-03 12:28:31,441 Adding items to [elasticsearch-url]/opnfv-confluence-raw/_bulk (in 1000 packs)
2020-04-03 12:28:33,337 Retrying (Retry(total=20, connect=21, read=7, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:28:34,151 Retrying (Retry(total=19, connect=21, read=6, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:28:35,381 Retrying (Retry(total=18, connect=21, read=5, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:28:37,407 Retrying (Retry(total=17, connect=21, read=4, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:28:41,036 Retrying (Retry(total=16, connect=21, read=3, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:28:47,869 Retrying (Retry(total=15, connect=21, read=2, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:29:01,092 Retrying (Retry(total=14, connect=21, read=1, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:29:27,121 Retrying (Retry(total=13, connect=21, read=0, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /opnfv-confluence-raw/_bulk?refresh=true
2020-04-03 12:29:27,556 Error feeding raw from confluence (https://wiki.opnfv.org): HTTPSConnectionPool(host='[elasticsearch-url]', port=9243): Max retries exceeded with url: /opnfv-confluence-raw/_bulk?refresh=true (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.5/ssl.py", line 899, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.5/ssl.py", line 869, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 594, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[elasticsearch-url]', port=9243): Max retries exceeded with url: /opnfv-confluence-raw/_bulk?refresh=true (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 234, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 258, in feed_items
    self._items_to_es(items_pack)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 291, in _items_to_es
    inserted = self.elastic.bulk_upload(json_items, field_id)
  File "/repos/grimoirelab-elk/grimoire_elk/elastic.py", line 351, in bulk_upload
    new_items += self.safe_put_bulk(url, bulk_json)
  File "/repos/grimoirelab-elk/grimoire_elk/elastic.py", line 182, in safe_put_bulk
    res = self.requests.put(url + '?refresh=true', data=bulk_json, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[elasticsearch-url]', port=9243): Max retries exceeded with url: /opnfv-confluence-raw/_bulk?refresh=true (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))
2020-04-03 12:29:27,573 [confluence] Done collection for https://wiki.opnfv.org
2020-04-03 12:29:27,573 Backend feed completed
```

**Comment by valeriocos** [comment]
Hi @code-sleuth ,

It seems that your instance doesn't have enough resources, try to decrease the bulk size to 10:
```
2020-04-03 12:28:31,441 Adding items to [elasticsearch-url]/opnfv-confluence-raw/_bulk (in 1000 packs)
```

Let me know how it goes, thanks!

**Comment by code-sleuth** [comment]
Hi @valeriocos thanks, that worked. But there's still missing data in the created index.
For example when i run the query below:
```
GET opnfv-confluence/_search
{
  "aggs": {
    "2": {
      "terms": {
        "field": "title",
        "order": {
          "_count": "desc"
        },
        "size": 100
      },
      "aggs": {
        "3": {
          "terms": {
            "field": "content_url",
            "order": {
              "_count": "desc"
            },
            "size": 100
          }
        }
      }
    }
  },
  "size": 0,
  "_source": {
    "excludes": []
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "date",
      "format": "date_time"
    },
    {
      "field": "grimoire_creation_date",
      "format": "date_time"
    },
    {
      "field": "metadata__enriched_on",
      "format": "date_time"
    },
    {
      "field": "metadata__timestamp",
      "format": "date_time"
    },
    {
      "field": "metadata__updated_on",
      "format": "date_time"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "type:page",
            "analyze_wildcard": true,
            "time_zone": "Africa/Nairobi"
          }
        },
        {
          "query_string": {
            "analyze_wildcard": true,
            "default_field": "*",
            "query": "*",
            "time_zone": "Africa/Nairobi"
          }
        }
      ],
      "filter": [
        {
          "match_all": {}
        },
        {
          "match_phrase": {
            "content_url": {
              "query": "https://wiki.opnfv.org/display/meetings/TSC"
            }
          }
        },
        {
          "range": {
            "grimoire_creation_date": {
              "format": "strict_date_optional_time",
              "gte": "2020-01-07T11:21:32.945Z",
              "lte": "2020-04-06T11:21:32.945Z"
            }
          }
        }
      ],
      "should": [],
      "must_not": [
        {
          "match_phrase": {
            "author_bot": {
              "query": true
            }
          }
        }
      ]
    }
  }
}
```
I get a `doc_count` of just 2 which is way off from what its supposed to be for the past 90 days.
Reference: https://wiki.opnfv.org/pages/viewpreviousversions.action?pageId=2925933

**Comment by valeriocos** [comment]
Hi @code-sleuth , which version of ELK are you using? 

Do you have some logs of the last execution?

Thanks

**Comment by code-sleuth** [comment]
**grimorelab-elk Version:** 0.70.0

**Comment by code-sleuth** [comment]
[logs.txt](https://github.com/chaoss/grimoirelab-elk/files/4439287/logs.txt)

**Comment by valeriocos** [comment]
Thank you for the info @code-sleuth . The logs seem clean.

Can you try to re-collect the data using new raw and enriched indexes? Thanks


I have tried an execution with [micro mordred](https://github.com/chaoss/grimoirelab-sirmordred#micro-mordred-) and the collection is executing smoothly (see configuration below).

 **snippet setup.cfg**
```
[confluence]
no-archive = true
raw_index = confluence_opnfv
enriched_index = confluence_opnfv_enriched
```

**snippet projects.json**
```   ..
        "confluence": [
            "https://wiki.opnfv.org/"
        ],
```

**Comment by lukaszgryglicki** [comment]
Missing data may be due to failure and then next subsequent runs continuing from the newest timestamp ever recorder.

**Comment by valeriocos** [comment]
@code-sleuth can we close this issue?

**Comment by code-sleuth** [comment]
yes, thanks for your support @valeriocos .

**Comment by valeriocos** [comment]
You're welcome @code-sleuth
