### ISSUE TITLE
pip package 0.26 up to date? missing backend in util.py (slack)

### ISSUE THREAD

**Issue by robinmuilwijk** [chaoss/grimoirelab-elk#83]
I upgraded my python packages yesterday, and I am now on grimoire-elk 0.26.5, perceval 0.7.0.

I upgraded so I can make use of the Slack backend. If I run my import script, all works, so I know the updates should be ok. Now I want to try this:

p2o.py --enrich --index slack_raw --index-enrich slack -e http://localhost:9200 --debug slack C06BF20AH --from-date 2015-06-01 -t my-slack-token

I get the follow errors:

2017-04-17 08:36:20,130 Debug mode activated
Traceback (most recent call last):
  File "/home/gelk/venvs/grimoirelab/bin/p2o.py", line 127, in <module>
    args.index, args.index_enrich, args.project)
  File "/home/gelk/venvs/grimoirelab/lib/python3.4/site-packages/grimoire_elk/arthur.py", line 53, in feed_backend
    raise RuntimeError("Unknown backend %s" % backend_name)
RuntimeError: Unknown backend slack
(grimoirelab) gelk@grim:~$

If I look in arthur.py, this gets its connector through utils.py. If I check this file, there is no import for slack. I can see this import on GitHub.

I am wondering if the grimoire-elk package on pypi contains this new file utils.py? Or am I doing something else wrong?

It looks like my utils.py is of an older version.

**Comment by robinmuilwijk** [comment]
p.s. I downloaded the package from https://pypi.python.org/pypi/grimoire-elk/0.26.5 and it does contain the correct utils.py which includes the slack import.

Could it be the pip3 install grimoire-elk --upgrade went wrong, and did not update this file?

**Comment by robinmuilwijk** [comment]
For some reason, it is working now. I ran the upgrade command again. I can verify the correct utils.py is now in place.
